
export const SET_RANDOM_NUMBER = 'SET_RANDOM_NUMBER'
export const SET_INPUT_NUMBER = 'SET_INPUT_NUMBER'
export const SET_COINS_MACHINE_5BAM = 'SET_COINS_MACHINE_5BAM'
export const SET_COINS_MACHINE_2BAM = 'SET_COINS_MACHINE_2BAM'
export const SET_COINS_MACHINE_1BAM = 'SET_COINS_MACHINE_1BAM'
export const SET_COINS_MACHINE_50PF = 'SET_COINS_MACHINE_50PF'
export const SET_COINS_MACHINE_20PF = 'SET_COINS_MACHINE_20PF'
export const SET_COINS_MACHINE_10PF = 'SET_COINS_MACHINE_10PF'





